import image from "../../assets/dosa_top_edit.png";

export const HardItemInMyCity = [
  {
    name: "Burger",
    image,
    price: 120,
    foodtype: "veg",
    rating: { count: 42 },
  },
  {
    name: "Pizza",
    image,
    price: 250,
    foodtype: "veg",
    rating: { count: 67 },
  },
  {
    name: "Biryani",
    image,
    price: 180,
    foodtype: "non-veg",
    rating: { count: 38 },
  },
  {
    name: "Pasta",
    image,
    price: 200,
    foodtype: "veg",
    rating: { count: 50 },
  },
  {
    name: "Sandwich",
    image,
    price: 150,
    foodtype: "veg",
    rating: { count: 25 },
  },
  {
    name: "Roll",
    image,
    price: 170,
    foodtype: "non-veg",
    rating: { count: 40 },
  },
  {
    name: "Burger",
    image,
    price: 120,
    foodtype: "veg",
    rating: { count: 42 },
  },
  {
    name: "Pizza",
    image,
    price: 250,
    foodtype: "veg",
    rating: { count: 67 },
  },
  {
    name: "Biryani",
    image,
    price: 180,
    foodtype: "non-veg",
    rating: { count: 38 },
  },
  {
    name: "Pasta",
    image,
    price: 200,
    foodtype: "veg",
    rating: { count: 50 },
  },
  {
    name: "Sandwich",
    image,
    price: 150,
    foodtype: "veg",
    rating: { count: 25 },
  },
  {
    name: "Roll",
    image,
    price: 170,
    foodtype: "non-veg",
    rating: { count: 40 },
  },
  {
    name: "Burger",
    image,
    price: 120,
    foodtype: "veg",
    rating: { count: 42 },
  },
  {
    name: "Pizza",
    image,
    price: 250,
    foodtype: "veg",
    rating: { count: 67 },
  },
  {
    name: "Biryani",
    image,
    price: 180,
    foodtype: "non-veg",
    rating: { count: 38 },
  },
  {
    name: "Pasta",
    image,
    price: 200,
    foodtype: "veg",
    rating: { count: 50 },
  },
  {
    name: "Sandwich",
    image,
    price: 150,
    foodtype: "veg",
    rating: { count: 25 },
  },
  {
    name: "Roll",
    image,
    price: 170,
    foodtype: "non-veg",
    rating: { count: 40 },
  },
  {
    name: "Burger",
    image,
    price: 120,
    foodtype: "veg",
    rating: { count: 42 },
  },
  {
    name: "Pizza",
    image,
    price: 250,
    foodtype: "veg",
    rating: { count: 67 },
  },
  {
    name: "Biryani",
    image,
    price: 180,
    foodtype: "non-veg",
    rating: { count: 38 },
  },
  {
    name: "Pasta",
    image,
    price: 200,
    foodtype: "veg",
    rating: { count: 50 },
  },
  {
    name: "Sandwich",
    image,
    price: 150,
    foodtype: "veg",
    rating: { count: 25 },
  },
  {
    name: "Roll",
    image,
    price: 170,
    foodtype: "non-veg",
    rating: { count: 40 },
  },
  {
    name: "Burger",
    image,
    price: 120,
    foodtype: "veg",
    rating: { count: 42 },
  },
  {
    name: "Pizza",
    image,
    price: 250,
    foodtype: "veg",
    rating: { count: 67 },
  },
  {
    name: "Biryani",
    image,
    price: 180,
    foodtype: "non-veg",
    rating: { count: 38 },
  },
  {
    name: "Pasta",
    image,
    price: 200,
    foodtype: "veg",
    rating: { count: 50 },
  },
  {
    name: "Sandwich",
    image,
    price: 150,
    foodtype: "veg",
    rating: { count: 25 },
  },
  {
    name: "Roll",
    image,
    price: 170,
    foodtype: "non-veg",
    rating: { count: 40 },
  },
  {
    name: "Burger",
    image,
    price: 120,
    foodtype: "veg",
    rating: { count: 42 },
  },
  {
    name: "Pizza",
    image,
    price: 250,
    foodtype: "veg",
    rating: { count: 67 },
  },
  {
    name: "Biryani",
    image,
    price: 180,
    foodtype: "non-veg",
    rating: { count: 38 },
  },
  {
    name: "Pasta",
    image,
    price: 200,
    foodtype: "veg",
    rating: { count: 50 },
  },
  {
    name: "Sandwich",
    image,
    price: 150,
    foodtype: "veg",
    rating: { count: 25 },
  },
  {
    name: "Roll",
    image,
    price: 170,
    foodtype: "non-veg",
    rating: { count: 40 },
  },
  {
    name: "Burger",
    image,
    price: 120,
    foodtype: "veg",
    rating: { count: 42 },
  },
  {
    name: "Pizza",
    image,
    price: 250,
    foodtype: "veg",
    rating: { count: 67 },
  },
  {
    name: "Biryani",
    image,
    price: 180,
    foodtype: "non-veg",
    rating: { count: 38 },
  },
  {
    name: "Pasta",
    image,
    price: 200,
    foodtype: "veg",
    rating: { count: 50 },
  },
  {
    name: "Sandwich",
    image,
    price: 150,
    foodtype: "veg",
    rating: { count: 25 },
  },
  {
    name: "Roll",
    image,
    price: 170,
    foodtype: "non-veg",
    rating: { count: 40 },
  },
  {
    name: "Burger",
    image,
    price: 120,
    foodtype: "veg",
    rating: { count: 42 },
  },
  {
    name: "Pizza",
    image,
    price: 250,
    foodtype: "veg",
    rating: { count: 67 },
  },
  {
    name: "Biryani",
    image,
    price: 180,
    foodtype: "non-veg",
    rating: { count: 38 },
  },
  {
    name: "Pasta",
    image,
    price: 200,
    foodtype: "veg",
    rating: { count: 50 },
  },
  {
    name: "Sandwich",
    image,
    price: 150,
    foodtype: "veg",
    rating: { count: 25 },
  },
  {
    name: "Roll",
    image,
    price: 170,
    foodtype: "non-veg",
    rating: { count: 40 },
  },
];
